// Package xberg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package xberg

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiKeyScope.
const (
	ApiKeyScopeRead  ApiKeyScope = "read"
	ApiKeyScopeWrite ApiKeyScope = "write"
)

// Valid indicates whether the value is a known member of the ApiKeyScope enum.
func (e ApiKeyScope) Valid() bool {
	switch e {
	case ApiKeyScopeRead:
		return true
	case ApiKeyScopeWrite:
		return true
	default:
		return false
	}
}

// Defines values for AuthMode.
const (
	AuthModeDisabled AuthMode = "disabled"
	AuthModeRequired AuthMode = "required"
)

// Valid indicates whether the value is a known member of the AuthMode enum.
func (e AuthMode) Valid() bool {
	switch e {
	case AuthModeDisabled:
		return true
	case AuthModeRequired:
		return true
	default:
		return false
	}
}

// Defines values for ProGetJobResponse0JobType.
const (
	ProGetJobResponse0JobTypeExtraction ProGetJobResponse0JobType = "extraction"
)

// Valid indicates whether the value is a known member of the ProGetJobResponse0JobType enum.
func (e ProGetJobResponse0JobType) Valid() bool {
	switch e {
	case ProGetJobResponse0JobTypeExtraction:
		return true
	default:
		return false
	}
}

// Defines values for ProGetJobResponse1JobType.
const (
	ProGetJobResponse1JobTypeCrawl ProGetJobResponse1JobType = "crawl"
)

// Valid indicates whether the value is a known member of the ProGetJobResponse1JobType enum.
func (e ProGetJobResponse1JobType) Valid() bool {
	switch e {
	case ProGetJobResponse1JobTypeCrawl:
		return true
	default:
		return false
	}
}

// Defines values for ProJobStatus.
const (
	ProJobStatusCancelled      ProJobStatus = "cancelled"
	ProJobStatusCompleted      ProJobStatus = "completed"
	ProJobStatusFailed         ProJobStatus = "failed"
	ProJobStatusPartialSuccess ProJobStatus = "partial_success"
	ProJobStatusPending        ProJobStatus = "pending"
	ProJobStatusProcessing     ProJobStatus = "processing"
)

// Valid indicates whether the value is a known member of the ProJobStatus enum.
func (e ProJobStatus) Valid() bool {
	switch e {
	case ProJobStatusCancelled:
		return true
	case ProJobStatusCompleted:
		return true
	case ProJobStatusFailed:
		return true
	case ProJobStatusPartialSuccess:
		return true
	case ProJobStatusPending:
		return true
	case ProJobStatusProcessing:
		return true
	default:
		return false
	}
}

// ApiKeyResponse API key details for list operations. Never includes the full key, only
// the prefix, for security.
type ApiKeyResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; always
	// `None` on Pro.
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Id Unique API key identifier.
	Id openapi_types.UUID `json:"id"`

	// KeyPrefix Key prefix for identification (e.g. `"kz_abcdefgh"`).
	KeyPrefix string `json:"key_prefix"`

	// LastUsedAt Optional last-used timestamp in ISO 8601 format.
	LastUsedAt *string `json:"last_used_at,omitempty"`

	// Name User-provided name for the key, when set.
	Name *string `json:"name,omitempty"`

	// RevokedAt Optional revocation timestamp in ISO 8601 format.
	RevokedAt *string `json:"revoked_at,omitempty"`

	// Scope What the key may do: `read` or `write`.
	Scope ApiKeyScope `json:"scope"`
}

// ApiKeyScope What an API key may do.
//
// A `Read` key is refused on every request whose HTTP method is not safe.
// The safe methods are GET, HEAD, OPTIONS and TRACE. A `Write` key has full
// access. The rule is the method, not the route, so a read that is shaped as a
// POST needs a `Write` key. The value is stored in `api_keys.scope` and
// carried on the wire in lowercase.
type ApiKeyScope string

// AuthConfigResponse `GET /auth/config` response: which auth methods this instance accepts.
type AuthConfigResponse struct {
	Identity *LocalIdentity `json:"identity,omitempty"`

	// Methods Accepted authentication methods (`"api_key"`, optionally `"oidc"`).
	Methods []string `json:"methods"`

	// Mode Explicit instance authentication policy; older servers require authentication.
	Mode *AuthMode `json:"mode,omitempty"`

	// Oidc OIDC-specific detail, used by the frontend to decide whether to render
	// a "Sign in with Google" button.
	Oidc OidcInfo `json:"oidc"`
}

// AuthMode Authentication policy advertised by the instance.
type AuthMode string

// BeginOAuthResponse OAuth connection response.
type BeginOAuthResponse struct {
	// AuthorizeUrl Provider authorization URL to send the user to.
	AuthorizeUrl string `json:"authorize_url"`
}

// CreateApiKeyRequest Request to create a new API key.
type CreateApiKeyRequest struct {
	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; Pro
	// leaves this unset (Pro-issued keys never expire).
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Name Descriptive name for the API key. Optional on Pro (unnamed keys are
	// allowed); Enterprise requires a non-empty name at the handler level.
	Name *string `json:"name,omitempty"`

	// Scope What the key may do. `read` keys are refused on POST, PUT, PATCH and
	// DELETE. Omitted means `write`.
	Scope *ApiKeyScope `json:"scope,omitempty"`
}

// CreateApiKeyResponse API key details returned only on creation/regeneration. `key` contains
// the full plaintext key and is only ever returned once.
type CreateApiKeyResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; always
	// `None` on Pro.
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Id Unique API key identifier.
	Id openapi_types.UUID `json:"id"`

	// Key Full API key. Only returned once, on creation/regeneration.
	Key string `json:"key"`

	// KeyPrefix Key prefix for identification.
	KeyPrefix string `json:"key_prefix"`

	// Kind Key kind (e.g. `"project"`, `"sandbox"`). Pro-only today; Enterprise
	// always issues `"project"` keys from this endpoint but does not surface
	// the kind on the wire.
	Kind *string `json:"kind,omitempty"`

	// Name User-provided name for the key, when set.
	Name *string `json:"name,omitempty"`

	// Scope What the key may do: `read` or `write`.
	Scope ApiKeyScope `json:"scope"`
}

// CreateIntegrationRequest Request to create an integration.
//
// Pro's own submission shape — see `api_types::CreateIntegrationRequest`'s
// module doc for the unreconciled drift versus Enterprise's `provider` +
// `client_id` + `client_secret` shape; adopting the shared request type is
// deferred pending a product decision, so this stays a Pro-local struct.
type CreateIntegrationRequest struct {
	AuthType string `json:"auth_type"`

	// Config Additional configuration as a JSON object (optional; mirrors the backend).
	Config *map[string]interface{} `json:"config,omitempty"`

	// Credentials BYO client credentials (client_id, client_secret for OAuth2/OIDC).
	Credentials map[string]interface{} `json:"credentials"`
	Kind        string                 `json:"kind"`
	Name        string                 `json:"name"`
}

// CreateProjectRequest Create a Pro project with a name, a required URL-safe slug and optional quota overrides.
type CreateProjectRequest struct {
	// MaxFileSizeMb Maximum upload file size (MB) override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxFileSizeMb *int32 `json:"max_file_size_mb,omitempty"`

	// MaxMonthlyJobs Monthly job quota override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxMonthlyJobs *int32 `json:"max_monthly_jobs,omitempty"`

	// MaxMonthlyPages Monthly page quota override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxMonthlyPages *int32 `json:"max_monthly_pages,omitempty"`

	// Name Project name.
	Name string `json:"name"`

	// Slug Required URL-safe project slug.
	Slug string `json:"slug"`
}

// DocumentResponse Single document's metadata, as reported by a connected integration.
type DocumentResponse struct {
	// Id Source-specific stable document identifier (opaque; format depends on
	// the connected integration, e.g. a Google Drive file id).
	Id string `json:"id"`

	// MimeType MIME type of the document.
	MimeType string `json:"mime_type"`

	// ModifiedAt Last-modified timestamp (RFC 3339), when reported by the source.
	ModifiedAt *string `json:"modified_at,omitempty"`

	// Name Human-readable document name.
	Name string `json:"name"`

	// SizeBytes Size in bytes, when reported by the source.
	SizeBytes *int64 `json:"size_bytes,omitempty"`
}

// IntegrationResponse Integration details for get/list/create responses. Never includes
// secrets or credentials, only integration metadata.
type IntegrationResponse struct {
	// AuthType Authentication type.
	AuthType string `json:"auth_type"`

	// Id Unique integration identifier.
	Id openapi_types.UUID `json:"id"`

	// Kind Integration kind.
	Kind string `json:"kind"`

	// Name User-friendly integration name.
	Name string `json:"name"`

	// ProjectId Owning project ID. Pro-only; Enterprise omits it (already scoped by
	// the request path).
	ProjectId *string `json:"project_id,omitempty"`

	// Provider Provider name.
	Provider string `json:"provider"`
}

// LicenseHealth Coarse license state for the unauthenticated health probe.
//
// Deliberately minimal: `/healthz` is reachable by anyone who can reach the
// port, unauthenticated, so it reports enough for a liveness probe to act on
// (is the license in a state that keeps this instance serving) and nothing
// an operator would consider an inventory — no expiry timestamp, no
// `features[]`. See `GET /v1/license` for the full, admin-only detail.
type LicenseHealth struct {
	// State "licensed", "grace", "expired", "invalid", or "unlicensed"
	State string `json:"state"`
}

// LicenseInfoResponse Full license detail for `GET /v1/license` — admin-only (ADR-0087 §5). Unlike
// `LicenseHealth`, this is behind authentication, so it can afford to name the licensee,
// license id, plan, expiry, grace window, and days remaining.
type LicenseInfoResponse struct {
	// DaysRemaining Days remaining before this state moves to the next harsher one — see
	// `LicenseState.days_remaining`. Absent for `expired`, `invalid`, and `unlicensed`.
	DaysRemaining *int64  `json:"days_remaining,omitempty"`
	ExpiresAt     *string `json:"expires_at,omitempty"`
	GraceDays     *int32  `json:"grace_days,omitempty"`

	// LicenseId Present for every state with claims to report (`licensed`, `grace`, `expired`).
	LicenseId *string `json:"license_id,omitempty"`
	Licensee  *string `json:"licensee,omitempty"`

	// Plan Display and support only — this build does not gate anything on `plan`.
	Plan *string `json:"plan,omitempty"`

	// State "licensed", "grace", "expired", "invalid", or "unlicensed"
	State string `json:"state"`
}

// ListApiKeysResponse Response for the paginated API key list endpoint.
type ListApiKeysResponse struct {
	// ApiKeys API keys in the current page.
	ApiKeys []ApiKeyResponse `json:"api_keys"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of API keys for the project.
	Total int64 `json:"total"`
}

// ListDocumentsResponse Response body for the integration document list endpoint.
//
// See the module-level doc for why this intentionally omits
// `total`/`limit`/`offset`.
type ListDocumentsResponse struct {
	// Documents Documents matching the filter, in source-reported order.
	Documents []DocumentResponse `json:"documents"`
}

// ListIntegrationsResponse Response for the paginated integration list endpoint.
type ListIntegrationsResponse struct {
	// Integrations Integrations in the current page.
	Integrations []IntegrationResponse `json:"integrations"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of integrations for the project.
	Total int64 `json:"total"`
}

// ListProjectsResponse Response for the paginated project list endpoint.
type ListProjectsResponse struct {
	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Projects Projects in the current page.
	Projects []ProjectResponse `json:"projects"`

	// Total Total number of projects for the caller.
	Total int64 `json:"total"`
}

// LocalIdentity Persisted local operator exposed only when authentication is disabled.
type LocalIdentity struct {
	// DefaultProjectId Persisted default workspace identifier.
	DefaultProjectId openapi_types.UUID `json:"default_project_id"`

	// Email No external identity provider supplies an email in this mode.
	Email *string `json:"email,omitempty"`

	// Name Display name of the local operator.
	Name string `json:"name"`

	// ProjectName Default workspace display name.
	ProjectName string `json:"project_name"`

	// Role Workspace role of the local operator.
	Role string `json:"role"`

	// UserId Local audit and project ownership principal.
	UserId string `json:"user_id"`
}

// LoginRequest Login request with an OIDC ID token (e.g. from Google/Firebase sign-in).
type LoginRequest struct {
	// IdToken ID token from the configured OIDC identity provider.
	IdToken string `json:"id_token"`
}

// LoginResponse Successful login response. Shape matches Xberg Enterprise backend's
// `LoginResponse` (`services/backend/src/handlers/auth.rs`) so the shared
// frontend auth action and generated TypeScript client work unchanged
// against either product.
type LoginResponse struct {
	// PendingInvitations Always `0` for Pro — there is no invitation system to defer against.
	PendingInvitations int32 `json:"pending_invitations"`

	// Project The user's active project. Always present for Pro (unlike Enterprise,
	// Pro has no pending-invitation state — every login has an active project
	// by the time this response is built, auto-provisioning one if needed).
	Project *ProjectInfo `json:"project,omitempty"`

	// Token Session JWT (valid for `jwt_expiration_secs`, default 7 days).
	Token string `json:"token"`

	// User Authenticated user information.
	User UserInfo `json:"user"`
}

// OidcInfo OIDC login configuration, as visible to an unauthenticated caller.
type OidcInfo struct {
	// Enabled Whether OIDC login is enabled at all.
	Enabled bool `json:"enabled"`

	// Issuer The configured OIDC issuer URL, or `None`.
	Issuer *string `json:"issuer,omitempty"`

	// Provider Provider label derived from the configured issuer (`"google"`,
	// `"github"`, `"firebase"`, `"oidc"`), or `None` when disabled or running
	// in mock mode without a configured issuer.
	Provider *string `json:"provider,omitempty"`
}

// ProExtractionJobResponse Metadata for one extraction job returned by `GET /v1/jobs/{id}`.
type ProExtractionJobResponse struct {
	// Cached Whether the result came from the server-side cache, when known.
	Cached *bool `json:"cached,omitempty"`

	// ChildJobIds Child extraction jobs created by document splitting.
	ChildJobIds *[]string `json:"child_job_ids,omitempty"`

	// CompletedAt ISO 8601 completion timestamp, when available.
	CompletedAt *string `json:"completed_at,omitempty"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Error Failure reason for a failed job.
	Error *string `json:"error,omitempty"`

	// Filename Original filename.
	Filename string `json:"filename"`

	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`

	// ImagesExtracted Images extracted, when recorded by the tier's persistence layer.
	ImagesExtracted *int32 `json:"images_extracted,omitempty"`

	// MimeType MIME type of the submitted document.
	MimeType string `json:"mime_type"`

	// PagesExtracted Pages extracted, when recorded by the tier's persistence layer.
	PagesExtracted *int32 `json:"pages_extracted,omitempty"`

	// ProcessingTimeMs Server-side processing duration in milliseconds.
	ProcessingTimeMs *int64             `json:"processing_time_ms,omitempty"`
	Result           *ExtractedDocument `json:"result,omitempty"`

	// Status Current job status.
	Status ProJobStatus `json:"status"`

	// TablesExtracted Tables extracted, when recorded by the tier's persistence layer.
	TablesExtracted *int32           `json:"tables_extracted,omitempty"`
	WebhookDelivery *WebhookDelivery `json:"webhook_delivery,omitempty"`
}

// ProGetJobResponse Canonical response for `GET /v1/jobs/{id}` on both product tiers.
//
// `job_type` is the stable wire discriminator. Keeping selection explicit
// lets clients accept future fields without making the variants ambiguous.
type ProGetJobResponse struct {
	union json.RawMessage
}

// ProGetJobResponse0 An extraction job.
type ProGetJobResponse0 struct {
	// Cached Whether the result came from the server-side cache, when known.
	Cached *bool `json:"cached,omitempty"`

	// ChildJobIds Child extraction jobs created by document splitting.
	ChildJobIds *[]string `json:"child_job_ids,omitempty"`

	// CompletedAt ISO 8601 completion timestamp, when available.
	CompletedAt *string `json:"completed_at,omitempty"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Error Failure reason for a failed job.
	Error *string `json:"error,omitempty"`

	// Filename Original filename.
	Filename string `json:"filename"`

	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`

	// ImagesExtracted Images extracted, when recorded by the tier's persistence layer.
	ImagesExtracted *int32                    `json:"images_extracted,omitempty"`
	JobType         ProGetJobResponse0JobType `json:"job_type"`

	// MimeType MIME type of the submitted document.
	MimeType string `json:"mime_type"`

	// PagesExtracted Pages extracted, when recorded by the tier's persistence layer.
	PagesExtracted *int32 `json:"pages_extracted,omitempty"`

	// ProcessingTimeMs Server-side processing duration in milliseconds.
	ProcessingTimeMs *int64             `json:"processing_time_ms,omitempty"`
	Result           *ExtractedDocument `json:"result,omitempty"`

	// Status Current job status.
	Status ProJobStatus `json:"status"`

	// TablesExtracted Tables extracted, when recorded by the tier's persistence layer.
	TablesExtracted *int32           `json:"tables_extracted,omitempty"`
	WebhookDelivery *WebhookDelivery `json:"webhook_delivery,omitempty"`
}

// ProGetJobResponse0JobType defines model for ProGetJobResponse.0.JobType.
type ProGetJobResponse0JobType string

// ProGetJobResponse1 A crawl job.
type ProGetJobResponse1 struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Id Crawl job identifier.
	Id      openapi_types.UUID        `json:"id"`
	JobType ProGetJobResponse1JobType `json:"job_type"`

	// Jobs Child extraction jobs.
	Jobs *[]CrawlChildJob `json:"jobs,omitempty"`

	// OutputMode Requested output mode.
	OutputMode string `json:"output_mode"`

	// Pages Retained raw pages.
	Pages *[]CrawledPage `json:"pages,omitempty"`

	// Progress Current progress counters.
	Progress CrawlProgress `json:"progress"`

	// SeedUrls Submitted seed URLs.
	SeedUrls []string `json:"seed_urls"`

	// Status Current crawl status.
	Status CrawlJobStatus `json:"status"`
}

// ProGetJobResponse1JobType defines model for ProGetJobResponse.1.JobType.
type ProGetJobResponse1JobType string

// ProHealthResponse Liveness + tier probe. The frontend reads `tier` for runtime feature gating.
type ProHealthResponse struct {
	// AutoTune Auto-tune readiness summary for the health response.
	AutoTune AutoTuneHealth `json:"auto_tune"`

	// License Coarse license state for the unauthenticated health probe.
	//
	// Deliberately minimal: `/healthz` is reachable by anyone who can reach the
	// port, unauthenticated, so it reports enough for a liveness probe to act on
	// (is the license in a state that keeps this instance serving) and nothing
	// an operator would consider an inventory — no expiry timestamp, no
	// `features[]`. See `GET /v1/license` for the full, admin-only detail.
	License LicenseHealth `json:"license"`

	// Rag RAG readiness summary for the health response.
	Rag    RagHealth `json:"rag"`
	Status string    `json:"status"`
	Tier   string    `json:"tier"`
}

// ProIntegrationListResponse Pro integration page and the instance's OAuth connection capability.
type ProIntegrationListResponse struct {
	// Integrations Integrations in the current page.
	Integrations []IntegrationResponse `json:"integrations"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// OauthConfigured Whether the integration hub is configured to establish OAuth connections.
	OauthConfigured bool `json:"oauth_configured"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of integrations for the project.
	Total int64 `json:"total"`
}

// ProJobResult Result envelope returned by GET /v1/jobs/{id}/result. The results array contains the extracted documents produced by this Pro job, in discovery order. The endpoint returns 409 until the job reaches completed or partial_success.
type ProJobResult struct {
	// Cached ~keep This job's recorded extraction-cache hit, independent of child jobs and billing.
	// ~keep False means no recorded hit; a pending job has not necessarily attempted extraction.
	Cached bool `json:"cached"`

	// CompletedAt ISO 8601 completion timestamp, when available.
	CompletedAt *string `json:"completed_at,omitempty"`

	// Errors Non-fatal per-document errors.
	Errors *[]JobResultError `json:"errors,omitempty"`

	// JobId The job this result belongs to.
	JobId openapi_types.UUID `json:"job_id"`

	// Results Extracted documents, present once the job reaches a terminal
	// successful state (`completed` or `partial_success`).
	//
	// Opaque JSON on purpose: each document is `xberg::types::ExtractedDocument`
	// plus the keys the structured pipeline merges in (`structured_output`,
	// `structured_output_flat`). Passing the stored document through untouched
	// is what keeps those keys on the wire; a typed round trip through the
	// engine's document type dropped every key that type does not declare.
	Results *[]JobResultDocument `json:"results,omitempty"`

	// Status Job status at the time the result was read.
	Status          ProJobStatus     `json:"status"`
	WebhookDelivery *WebhookDelivery `json:"webhook_delivery,omitempty"`
}

// ProJobStatus Lifecycle status of a Pro extraction job, serialized as snake_case.
type ProJobStatus string

// ProJobSummary Summary of a job, as returned by `GET /v1/jobs` (list).
type ProJobSummary struct {
	// CompletedAt ISO 8601 completion timestamp, present once the job reaches a
	// terminal state.
	CompletedAt *string `json:"completed_at,omitempty"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Filename Original filename.
	Filename string `json:"filename"`

	// Id Unique job identifier.
	Id openapi_types.UUID `json:"id"`

	// MimeType MIME type of the submitted document.
	MimeType string `json:"mime_type"`

	// Status Current job status.
	Status          ProJobStatus     `json:"status"`
	WebhookDelivery *WebhookDelivery `json:"webhook_delivery,omitempty"`
}

// ProListJobsResponse Response for `GET /v1/jobs` (paginated job list).
type ProListJobsResponse struct {
	// Jobs Jobs in the current page, most recent first.
	Jobs []ProJobSummary `json:"jobs"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of jobs for the project.
	Total int64 `json:"total"`
}

// ProPresignUploadRequest Request body for presigning upload URLs.
type ProPresignUploadRequest struct {
	// Config Batch-level extraction configuration (applied to all documents).
	Config *map[string]interface{} `json:"config,omitempty"`

	// Documents Document metadata (no file data)
	Documents []PresignDocumentInput `json:"documents"`

	// Webhook Webhook configuration for async result delivery
	Webhook *WebhookConfig `json:"webhook,omitempty"`
}

// ProReadinessChecks Per-dependency readiness results.
type ProReadinessChecks struct {
	// Database `ok` or `unhealthy`: a connection was checked out of the pool.
	Database string `json:"database"`

	// MaintenanceDatabase `ok` or `unhealthy`: the maintenance login acquired a connection.
	MaintenanceDatabase string `json:"maintenance_database"`

	// Storage `ok` or `unhealthy`: the object store answered a metadata request. A
	// refusal counts as an answer; the check proves reachability, not
	// credentials.
	Storage string `json:"storage"`

	// Worker `ok` or `not_ready`: the embedded vector-index worker answered its own
	// readiness endpoint with success. A worker that answers not ready, or not
	// at all, is `not_ready`. Absent when the process runs without a worker.
	Worker *string `json:"worker,omitempty"`
}

// ProReadinessResponse Readiness report: the process can serve traffic only when both checks pass.
type ProReadinessResponse struct {
	// Checks Per-dependency readiness results.
	Checks ProReadinessChecks `json:"checks"`

	// Status `ready` or `not_ready`
	Status string `json:"status"`
}

// ProjectInfo Project information in the login response.
type ProjectInfo struct {
	// Id Project UUID.
	Id openapi_types.UUID `json:"id"`

	// Name Project name.
	Name string `json:"name"`

	// Role User role for this session (`OWNER` or `MEMBER`). See
	// `compute_role` for how this is derived.
	Role string `json:"role"`
}

// ProjectResponse Project details, as returned by create/get/list.
//
// Mirrors the Enterprise backend's `ProjectResponse` exactly. Pro's current
// HTTP DTOs (`ProjectSummary`, `CreateProjectResponse`) expose a subset of
// these fields, but Pro's `persistence::ProjectSummary` model already tracks
// every one of them (`owner_user_id`, `api_key_count`, `webhook_count`,
// `total_pages_extracted`) — adopting this full shape is a handler-level
// wiring change, not a schema gap, so no field here is `Option`.
type ProjectResponse struct {
	// ApiKeyCount Number of active (non-revoked) API keys.
	ApiKeyCount int32 `json:"api_key_count"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique project identifier.
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable project name.
	Name string `json:"name"`

	// OwnerUserId User ID of the project owner (from the identity provider).
	OwnerUserId string `json:"owner_user_id"`

	// Slug URL-safe identifier.
	Slug string `json:"slug"`

	// Status Project status (e.g. `"ACTIVE"`, `"SUSPENDED"`, `"INACTIVE"`).
	Status string `json:"status"`

	// TotalPagesExtracted Total billable pages extracted (excluding cancelled jobs).
	TotalPagesExtracted int64 `json:"total_pages_extracted"`

	// UpdatedAt ISO 8601 last update timestamp.
	UpdatedAt time.Time `json:"updated_at"`

	// WebhookCount Number of active (non-deleted) webhooks.
	WebhookCount int32 `json:"webhook_count"`
}

// RagConfigResponse A project's RAG configuration, as returned by `GET .../rag-config` and
// `PUT .../rag-config`.
//
// A plain, sqlx-free mirror of `common::ProjectRagConfig` — `api-types` must
// not depend on `sqlx`/`tokio-postgres`, so the shape is duplicated here
// rather than shared.
type RagConfigResponse struct {
	// DefaultCollection Default vector collection for RAG operations.
	DefaultCollection *string `json:"default_collection,omitempty"`

	// Enabled Whether RAG is enabled for this project.
	Enabled bool `json:"enabled"`
}

// RagHealth RAG readiness summary for the health response.
type RagHealth struct {
	// Enabled Whether the in-process RAG runtime is wired. Mirrors
	// `crate::rag::rag_runtime_enabled` at boot time — `false` means every
	// `/v1/rag/*` request 404s with `rag.disabled` regardless of any
	// individual project's own RAG config.
	Enabled bool `json:"enabled"`
}

// SetRagConfigRequest Request to set a project's RAG configuration (`PUT .../rag-config`).
type SetRagConfigRequest struct {
	// DefaultCollection Default vector collection for RAG operations.
	DefaultCollection *string `json:"default_collection,omitempty"`

	// Enabled Whether RAG should be enabled for this project.
	Enabled bool `json:"enabled"`
}

// UserInfo User information in the login response.
type UserInfo struct {
	// DefaultProjectId The user's active project id.
	DefaultProjectId *openapi_types.UUID `json:"default_project_id,omitempty"`

	// Email User email address.
	Email *string `json:"email,omitempty"`

	// Name User display name.
	Name *string `json:"name,omitempty"`

	// UserId User id from the identity provider (OIDC `sub`).
	UserId string `json:"user_id"`
}

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	// Code Authorization code from the provider
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State Signed state token issued by the connect call
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Provider error code when the user denied access
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListIntegrationsParams defines parameters for ListIntegrations.
type ListIntegrationsParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListIntegrationDocumentsParams defines parameters for ListIntegrationDocuments.
type ListIntegrationDocumentsParams struct {
	// MimeTypes Comma-separated MIME types to filter by (empty = all types).
	MimeTypes *string `form:"mime_types,omitempty" json:"mime_types,omitempty"`

	// FolderId Source-specific folder ID to scope listing.
	FolderId *string `form:"folder_id,omitempty" json:"folder_id,omitempty"`

	// Limit Maximum number of documents to return.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of matching documents to skip.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateIntegrationJSONRequestBody defines body for CreateIntegration for application/json ContentType.
type CreateIntegrationJSONRequestBody = CreateIntegrationRequest

// SetRagConfigJSONRequestBody defines body for SetRagConfig for application/json ContentType.
type SetRagConfigJSONRequestBody = SetRagConfigRequest

// AsProGetJobResponse0 returns the union data inside the ProGetJobResponse as a ProGetJobResponse0
func (t ProGetJobResponse) AsProGetJobResponse0() (ProGetJobResponse0, error) {
	var body ProGetJobResponse0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProGetJobResponse0 overwrites any union data inside the ProGetJobResponse as the provided ProGetJobResponse0
func (t *ProGetJobResponse) FromProGetJobResponse0(v ProGetJobResponse0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProGetJobResponse0 performs a merge with any union data inside the ProGetJobResponse, using the provided ProGetJobResponse0
func (t *ProGetJobResponse) MergeProGetJobResponse0(v ProGetJobResponse0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProGetJobResponse1 returns the union data inside the ProGetJobResponse as a ProGetJobResponse1
func (t ProGetJobResponse) AsProGetJobResponse1() (ProGetJobResponse1, error) {
	var body ProGetJobResponse1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProGetJobResponse1 overwrites any union data inside the ProGetJobResponse as the provided ProGetJobResponse1
func (t *ProGetJobResponse) FromProGetJobResponse1(v ProGetJobResponse1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProGetJobResponse1 performs a merge with any union data inside the ProGetJobResponse, using the provided ProGetJobResponse1
func (t *ProGetJobResponse) MergeProGetJobResponse1(v ProGetJobResponse1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ProGetJobResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ProGetJobResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
