// Package xberg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package xberg

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApiKeyScope.
const (
	Read  ApiKeyScope = "read"
	Write ApiKeyScope = "write"
)

// Valid indicates whether the value is a known member of the ApiKeyScope enum.
func (e ApiKeyScope) Valid() bool {
	switch e {
	case Read:
		return true
	case Write:
		return true
	default:
		return false
	}
}

// ApiKeyResponse API key details for list operations. Never includes the full key, only
// the prefix, for security.
type ApiKeyResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; always
	// `None` on Pro.
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Id Unique API key identifier.
	Id openapi_types.UUID `json:"id"`

	// KeyPrefix Key prefix for identification (e.g. `"kz_abcdefgh"`).
	KeyPrefix string `json:"key_prefix"`

	// LastUsedAt Optional last-used timestamp in ISO 8601 format.
	LastUsedAt *string `json:"last_used_at,omitempty"`

	// Name User-provided name for the key, when set.
	Name *string `json:"name,omitempty"`

	// RevokedAt Optional revocation timestamp in ISO 8601 format.
	RevokedAt *string `json:"revoked_at,omitempty"`

	// Scope What the key may do: `read` or `write`.
	Scope ApiKeyScope `json:"scope"`
}

// ApiKeyScope What an API key may do.
//
// A `Read` key is refused on every request whose HTTP method is not safe.
// The safe methods are GET, HEAD, OPTIONS and TRACE. A `Write` key has full
// access. The rule is the method, not the route, so a read that is shaped as a
// POST needs a `Write` key. The value is stored in `api_keys.scope` and
// carried on the wire in lowercase.
type ApiKeyScope string

// AuthConfigResponse `GET /auth/config` response: which auth methods this instance accepts.
type AuthConfigResponse struct {
	// Methods Accepted authentication methods (`"api_key"`, optionally `"oidc"`).
	Methods []string `json:"methods"`

	// Oidc OIDC-specific detail, used by the frontend to decide whether to render
	// a "Sign in with Google" button.
	Oidc OidcInfo `json:"oidc"`
}

// BeginOAuthResponse OAuth connection response.
type BeginOAuthResponse struct {
	// AuthorizeUrl Provider authorization URL to send the user to.
	AuthorizeUrl string `json:"authorize_url"`
}

// CreateApiKeyRequest Request to create a new API key.
type CreateApiKeyRequest struct {
	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; Pro
	// leaves this unset (Pro-issued keys never expire).
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Name Descriptive name for the API key. Optional on Pro (unnamed keys are
	// allowed); Enterprise requires a non-empty name at the handler level.
	Name *string `json:"name,omitempty"`

	// Scope What the key may do. `read` keys are refused on POST, PUT, PATCH and
	// DELETE. Omitted means `write`.
	Scope *ApiKeyScope `json:"scope,omitempty"`
}

// CreateApiKeyResponse API key details returned only on creation/regeneration. `key` contains
// the full plaintext key and is only ever returned once.
type CreateApiKeyResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt Optional expiration date in ISO 8601 format. Enterprise-only; always
	// `None` on Pro.
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Id Unique API key identifier.
	Id openapi_types.UUID `json:"id"`

	// Key Full API key. Only returned once, on creation/regeneration.
	Key string `json:"key"`

	// KeyPrefix Key prefix for identification.
	KeyPrefix string `json:"key_prefix"`

	// Kind Key kind (e.g. `"project"`, `"sandbox"`). Pro-only today; Enterprise
	// always issues `"project"` keys from this endpoint but does not surface
	// the kind on the wire.
	Kind *string `json:"kind,omitempty"`

	// Name User-provided name for the key, when set.
	Name *string `json:"name,omitempty"`

	// Scope What the key may do: `read` or `write`.
	Scope ApiKeyScope `json:"scope"`
}

// CreateIntegrationRequest Request to create an integration.
//
// Pro's own submission shape — see `api_types::CreateIntegrationRequest`'s
// module doc for the unreconciled drift versus Enterprise's `provider` +
// `client_id` + `client_secret` shape; adopting the shared request type is
// deferred pending a product decision, so this stays a Pro-local struct.
type CreateIntegrationRequest struct {
	AuthType string `json:"auth_type"`

	// Config Additional configuration as a JSON object (optional; mirrors the backend).
	Config *map[string]interface{} `json:"config,omitempty"`

	// Credentials BYO client credentials (client_id, client_secret for OAuth2/OIDC).
	Credentials map[string]interface{} `json:"credentials"`
	Kind        string                 `json:"kind"`
	Name        string                 `json:"name"`
}

// CreateProjectRequest Request to create a new project.
//
// `name` is the only field the Enterprise backend accepts — it derives a
// unique slug server-side. Pro's control plane requires the caller to supply
// `slug` directly and additionally accepts per-project quota overrides;
// those fields are optional here and are Pro-only until Enterprise grows the
// same override capability.
type CreateProjectRequest struct {
	// MaxFileSizeMb Maximum upload file size (MB) override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxFileSizeMb *int32 `json:"max_file_size_mb,omitempty"`

	// MaxMonthlyJobs Monthly job quota override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxMonthlyJobs *int32 `json:"max_monthly_jobs,omitempty"`

	// MaxMonthlyPages Monthly page quota override. Pro-only; Enterprise applies a
	// service-wide default instead.
	MaxMonthlyPages *int32 `json:"max_monthly_pages,omitempty"`

	// Name Project name.
	Name string `json:"name"`

	// Slug URL-safe project slug. Enterprise-only omission: Enterprise derives a
	// unique slug from `name` server-side and rejects this field being
	// meaningfully used; Pro requires the caller to supply it.
	Slug *string `json:"slug,omitempty"`
}

// DocumentResponse Single document's metadata, as reported by a connected integration.
type DocumentResponse struct {
	// Id Source-specific stable document identifier (opaque; format depends on
	// the connected integration, e.g. a Google Drive file id).
	Id string `json:"id"`

	// MimeType MIME type of the document.
	MimeType string `json:"mime_type"`

	// ModifiedAt Last-modified timestamp (RFC 3339), when reported by the source.
	ModifiedAt *string `json:"modified_at,omitempty"`

	// Name Human-readable document name.
	Name string `json:"name"`

	// SizeBytes Size in bytes, when reported by the source.
	SizeBytes *int64 `json:"size_bytes,omitempty"`
}

// GetJobResponse Job metadata returned by `GET /v1/jobs/{id}`.
type GetJobResponse struct {
	Cached      bool      `json:"cached"`
	CompletedAt *string   `json:"completed_at,omitempty"`
	CreatedAt   time.Time `json:"created_at"`

	// Error Failure reason for a failed job, from the most recent recorded error.
	Error           *string            `json:"error,omitempty"`
	Filename        string             `json:"filename"`
	Id              openapi_types.UUID `json:"id"`
	ImagesExtracted *int32             `json:"images_extracted,omitempty"`
	MimeType        string             `json:"mime_type"`
	PagesExtracted  *int32             `json:"pages_extracted,omitempty"`

	// ProcessingTimeMs Wall-clock processing time. Named as on Enterprise's job response.
	ProcessingTimeMs *int64 `json:"processing_time_ms,omitempty"`

	// Status Lifecycle status of an extraction job.
	//
	// Mirrors `domain::jobs::DomainJobStatus` and the Enterprise-local
	// `services/api::rest::jobs::JobStatus` enum. Defined independently here
	// rather than depending on `crates/domain`: `domain` pulls in the database,
	// storage, and NATS stacks, which would be an inappropriate dependency
	// weight for a thin wire-types crate.
	//
	// Wire form is `snake_case` (`"completed"`, `"partial_success"`), matching
	// Enterprise's current serialization. **Pro migration note:** Pro currently
	// emits UPPERCASE status strings, so adopting this enum lower-cases them — a
	// breaking wire change for existing Pro clients (see ADR-0066).
	Status          JobStatus `json:"status"`
	TablesExtracted *int32    `json:"tables_extracted,omitempty"`
}

// HealthResponse Liveness + tier probe. The frontend reads `tier` for runtime feature gating.
type HealthResponse struct {
	// AutoTune Auto-tune readiness summary for the health response.
	AutoTune AutoTuneHealth `json:"auto_tune"`

	// License License info summary for the health response.
	License LicenseHealth `json:"license"`

	// Rag RAG readiness summary for the health response.
	Rag    RagHealth `json:"rag"`
	Status string    `json:"status"`
	Tier   string    `json:"tier"`
}

// IntegrationResponse Integration details for get/list/create responses. Never includes
// secrets or credentials, only integration metadata.
type IntegrationResponse struct {
	// AuthType Authentication type.
	AuthType string `json:"auth_type"`

	// Id Unique integration identifier.
	Id openapi_types.UUID `json:"id"`

	// Kind Integration kind.
	Kind string `json:"kind"`

	// Name User-friendly integration name.
	Name string `json:"name"`

	// ProjectId Owning project ID. Pro-only; Enterprise omits it (already scoped by
	// the request path).
	ProjectId *string `json:"project_id,omitempty"`

	// Provider Provider name.
	Provider string `json:"provider"`
}

// LicenseHealth License info summary for the health response.
type LicenseHealth struct {
	// ExpiresAt Optional: expiry timestamp if available
	ExpiresAt *string `json:"expires_at,omitempty"`

	// Features Optional: features list if licensed
	Features *[]string `json:"features,omitempty"`

	// State "licensed", "expired", "invalid", or "unlicensed"
	State string `json:"state"`
}

// ListApiKeysResponse Response for the paginated API key list endpoint.
type ListApiKeysResponse struct {
	// ApiKeys API keys in the current page.
	ApiKeys []ApiKeyResponse `json:"api_keys"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of API keys for the project.
	Total int64 `json:"total"`
}

// ListDocumentsResponse Response body for the integration document list endpoint.
//
// See the module-level doc for why this intentionally omits
// `total`/`limit`/`offset`.
type ListDocumentsResponse struct {
	// Documents Documents matching the filter, in source-reported order.
	Documents []DocumentResponse `json:"documents"`
}

// ListIntegrationsResponse Response for the paginated integration list endpoint.
type ListIntegrationsResponse struct {
	// Integrations Integrations in the current page.
	Integrations []IntegrationResponse `json:"integrations"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of integrations for the project.
	Total int64 `json:"total"`
}

// ListProjectsResponse Response for the paginated project list endpoint.
type ListProjectsResponse struct {
	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Projects Projects in the current page.
	Projects []ProjectResponse `json:"projects"`

	// Total Total number of projects for the caller.
	Total int64 `json:"total"`
}

// LoginRequest Login request with an OIDC ID token (e.g. from Google/Firebase sign-in).
type LoginRequest struct {
	// IdToken ID token from the configured OIDC identity provider.
	IdToken string `json:"id_token"`
}

// LoginResponse Successful login response. Shape matches Xberg Enterprise backend's
// `LoginResponse` (`services/backend/src/handlers/auth.rs`) so the shared
// frontend auth action and generated TypeScript client work unchanged
// against either product.
type LoginResponse struct {
	// PendingInvitations Always `0` for Pro — there is no invitation system to defer against.
	PendingInvitations int32 `json:"pending_invitations"`

	// Project The user's active project. Always present for Pro (unlike Enterprise,
	// Pro has no pending-invitation state — every login has an active project
	// by the time this response is built, auto-provisioning one if needed).
	Project *ProjectInfo `json:"project,omitempty"`

	// Token Session JWT (valid for `jwt_expiration_secs`, default 7 days).
	Token string `json:"token"`

	// User Authenticated user information.
	User UserInfo `json:"user"`
}

// OidcInfo OIDC login configuration, as visible to an unauthenticated caller.
type OidcInfo struct {
	// Enabled Whether OIDC login is enabled at all.
	Enabled bool `json:"enabled"`

	// Issuer The configured OIDC issuer URL, or `None`.
	Issuer *string `json:"issuer,omitempty"`

	// Provider Provider label derived from the configured issuer (`"google"`,
	// `"github"`, `"firebase"`, `"oidc"`), or `None` when disabled or running
	// in mock mode without a configured issuer.
	Provider *string `json:"provider,omitempty"`
}

// ProReadinessChecks Per-dependency readiness results.
type ProReadinessChecks struct {
	// Database `ok` or `unhealthy`: a connection was checked out of the pool.
	Database string `json:"database"`

	// MaintenanceDatabase `ok` or `unhealthy`: the maintenance login acquired a connection.
	MaintenanceDatabase string `json:"maintenance_database"`

	// Storage `ok` or `unhealthy`: the object store answered a metadata request. A
	// refusal counts as an answer; the check proves reachability, not
	// credentials.
	Storage string `json:"storage"`
}

// ProReadinessResponse Readiness report: the process can serve traffic only when both checks pass.
type ProReadinessResponse struct {
	// Checks Per-dependency readiness results.
	Checks ProReadinessChecks `json:"checks"`

	// Status `ready` or `not_ready`
	Status string `json:"status"`
}

// ProjectInfo Project information in the login response.
type ProjectInfo struct {
	// Id Project UUID.
	Id openapi_types.UUID `json:"id"`

	// Name Project name.
	Name string `json:"name"`

	// Role User role for this session (`OWNER` or `MEMBER`). See
	// [`compute_role`] for how this is derived.
	Role string `json:"role"`
}

// ProjectResponse Project details, as returned by create/get/list.
//
// Mirrors the Enterprise backend's `ProjectResponse` exactly. Pro's current
// HTTP DTOs (`ProjectSummary`, `CreateProjectResponse`) expose a subset of
// these fields, but Pro's `persistence::ProjectSummary` model already tracks
// every one of them (`owner_user_id`, `api_key_count`, `webhook_count`,
// `total_pages_extracted`) — adopting this full shape is a handler-level
// wiring change, not a schema gap, so no field here is `Option`.
type ProjectResponse struct {
	// ApiKeyCount Number of active (non-revoked) API keys.
	ApiKeyCount int32 `json:"api_key_count"`

	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// Id Unique project identifier.
	Id openapi_types.UUID `json:"id"`

	// Name Human-readable project name.
	Name string `json:"name"`

	// OwnerUserId User ID of the project owner (from the identity provider).
	OwnerUserId string `json:"owner_user_id"`

	// Slug URL-safe identifier.
	Slug string `json:"slug"`

	// Status Project status (e.g. `"ACTIVE"`, `"SUSPENDED"`, `"INACTIVE"`).
	Status string `json:"status"`

	// TotalPagesExtracted Total billable pages extracted (excluding cancelled jobs).
	TotalPagesExtracted int64 `json:"total_pages_extracted"`

	// UpdatedAt ISO 8601 last update timestamp.
	UpdatedAt time.Time `json:"updated_at"`

	// WebhookCount Number of active (non-deleted) webhooks.
	WebhookCount int32 `json:"webhook_count"`
}

// RagConfigResponse A project's RAG configuration, as returned by `GET .../rag-config` and
// `PUT .../rag-config`.
//
// A plain, sqlx-free mirror of `common::ProjectRagConfig` — `api-types` must
// not depend on `sqlx`/`tokio-postgres`, so the shape is duplicated here
// rather than shared.
type RagConfigResponse struct {
	// DefaultCollection Default vector collection for RAG operations.
	DefaultCollection *string `json:"default_collection,omitempty"`

	// Enabled Whether RAG is enabled for this project.
	Enabled bool `json:"enabled"`
}

// RagHealth RAG readiness summary for the health response.
type RagHealth struct {
	// Enabled Whether the in-process RAG runtime is wired. Mirrors
	// `crate::rag::rag_feature_licensed` at boot time — `false` means every
	// `/v1/rag/*` request 404s with `rag.disabled` regardless of any
	// individual project's own RAG config.
	Enabled bool `json:"enabled"`
}

// SetRagConfigRequest Request to set a project's RAG configuration (`PUT .../rag-config`).
type SetRagConfigRequest struct {
	// DefaultCollection Default vector collection for RAG operations.
	DefaultCollection *string `json:"default_collection,omitempty"`

	// Enabled Whether RAG should be enabled for this project.
	Enabled bool `json:"enabled"`
}

// UserInfo User information in the login response.
type UserInfo struct {
	// DefaultProjectId The user's active project id.
	DefaultProjectId *openapi_types.UUID `json:"default_project_id,omitempty"`

	// Email User email address.
	Email *string `json:"email,omitempty"`

	// Name User display name.
	Name *string `json:"name,omitempty"`

	// UserId User id from the identity provider (OIDC `sub`).
	UserId string `json:"user_id"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	// Action Filter to entries matching this action exactly (e.g. `"job.submit"`).
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Limit Page size. Values outside 1..=100 are clamped into range rather than
	// rejected.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A value above 1,000,000 is clamped to
	// 1,000,000, which selects an empty page.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	// Code Authorization code from the provider
	Code *string `form:"code,omitempty" json:"code,omitempty"`

	// State Signed state token issued by the connect call
	State *string `form:"state,omitempty" json:"state,omitempty"`

	// Error Provider error code when the user denied access
	Error *string `form:"error,omitempty" json:"error,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListApiKeysParams defines parameters for ListApiKeys.
type ListApiKeysParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListIntegrationsParams defines parameters for ListIntegrations.
type ListIntegrationsParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListIntegrationDocumentsParams defines parameters for ListIntegrationDocuments.
type ListIntegrationDocumentsParams struct {
	// MimeTypes Comma-separated MIME types to keep; empty keeps all
	MimeTypes *string `form:"mime_types,omitempty" json:"mime_types,omitempty"`

	// FolderId Source-specific folder ID to list
	FolderId *string `form:"folder_id,omitempty" json:"folder_id,omitempty"`

	// MaxResults Maximum number of documents (clamped to 1000)
	MaxResults *int `form:"max_results,omitempty" json:"max_results,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateIntegrationJSONRequestBody defines body for CreateIntegration for application/json ContentType.
type CreateIntegrationJSONRequestBody = CreateIntegrationRequest

// SetRagConfigJSONRequestBody defines body for SetRagConfig for application/json ContentType.
type SetRagConfigJSONRequestBody = SetRagConfigRequest
