// Package xberg provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package xberg

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AcceptInvitationRequest Request to accept an invitation using its token.
type AcceptInvitationRequest struct {
	// Token Invitation token received via email.
	Token string `json:"token"`
}

// AnalyticsQuery Query parameters for analytics endpoint
type AnalyticsQuery struct {
	// EndDate End date (ISO 8601 format, e.g., "2025-01-31")
	EndDate string `json:"end_date"`

	// StartDate Start date (ISO 8601 format, e.g., "2025-01-01")
	StartDate string `json:"start_date"`
}

// AnalyticsResponse Analytics response containing daily metrics
type AnalyticsResponse struct {
	// Days Daily analytics entries
	Days []DailyAnalyticsEntry `json:"days"`

	// EndDate End date of the analytics period
	EndDate string `json:"end_date"`

	// ProjectId The project identifier
	ProjectId string `json:"project_id"`

	// StartDate Start date of the analytics period
	StartDate string `json:"start_date"`
}

// BackendCreateIntegrationRequest Request to create a new integration.
//
// See the module-level doc for the unreconciled credential-submission
// drift between Enterprise (`provider` + `client_id` + `client_secret`) and
// Pro (`credentials` JSON blob).
type BackendCreateIntegrationRequest struct {
	// AuthType Authentication type: `"none"`, `"static"`, `"api_key"`, `"oauth2"`, or `"oidc"`.
	AuthType string `json:"auth_type"`

	// ClientId Client ID or username. Enterprise-only submission shape.
	ClientId *string `json:"client_id,omitempty"`

	// ClientSecret Client secret or password. Enterprise-only submission shape.
	ClientSecret *string `json:"client_secret,omitempty"`

	// Config Additional configuration as a JSON object.
	Config *map[string]interface{} `json:"config,omitempty"`

	// Credentials Free-form BYO credentials object (e.g. `client_id`/`client_secret` as
	// object keys). Pro-only submission shape.
	Credentials *map[string]interface{} `json:"credentials,omitempty"`

	// Kind Integration kind (e.g. `"stripe"`, `"hubspot"`, `"google_drive"`).
	Kind string `json:"kind"`

	// Name Integration name (user-friendly identifier).
	Name string `json:"name"`

	// Provider Provider name, must match a catalog entry. Enterprise-only; Pro
	// derives the provider from the created record instead of the request.
	Provider *string `json:"provider,omitempty"`
}

// BackendHealthResponse Liveness response body: process status plus a service-supplied deployment tier.
//
// The `tier` seam lets each service report its own value — `api` reads it
// from `AppState.tier`, `backend` reads the `DEPLOYMENT_TIER` env var — while
// both share the identical JSON shape and (with the `openapi` feature)
// `utoipa` schema.
type BackendHealthResponse struct {
	// Status Service status
	Status string `json:"status"`

	// Tier Deployment tier the frontend uses for runtime feature gating (ADR-0047).
	Tier string `json:"tier"`
}

// BackendReadinessChecks Individual dependency check results
type BackendReadinessChecks struct {
	// Database Database connectivity
	Database string `json:"database"`

	// MaintenanceDatabase Maintenance database connectivity.
	MaintenanceDatabase string `json:"maintenance_database"`
}

// BackendReadinessResponse Readiness check response with dependency status
type BackendReadinessResponse struct {
	// Checks Dependency check results
	Checks BackendReadinessChecks `json:"checks"`

	// Status Overall readiness status
	Status string `json:"status"`
}

// BackendUsageResponse Response containing usage statistics
type BackendUsageResponse struct {
	// ByMethod Request count by HTTP method
	ByMethod map[string]int64 `json:"by_method"`

	// ByPath Request count by path (normalized)
	ByPath map[string]int64 `json:"by_path"`

	// ByStatusCode Request count by status code
	ByStatusCode map[string]int64 `json:"by_status_code"`

	// ErrorDetails Recent error details (up to 100)
	ErrorDetails []ErrorDetail `json:"error_details"`

	// Period Time period covered by these statistics
	Period UsagePeriod `json:"period"`

	// ProjectId The project identifier
	ProjectId string `json:"project_id"`

	// Summary Aggregated statistics for the period
	Summary UsageSummary `json:"summary"`
}

// BeginConnectResponse OAuth authorization initiation response
type BeginConnectResponse struct {
	// AuthorizeUrl Authorization URL to redirect the user to
	AuthorizeUrl string `json:"authorize_url"`
}

// BillingAccountInfo Stripe billing account information
type BillingAccountInfo struct {
	// CancelAt ISO 8601 datetime when the subscription is scheduled to cancel.
	// Null when no cancellation is pending.
	CancelAt *string `json:"cancel_at,omitempty"`

	// CancelAtPeriodEnd True when the user has scheduled a deferred cancellation via the Stripe portal.
	// The subscription stays active until cancel_at / period end.
	CancelAtPeriodEnd bool `json:"cancel_at_period_end"`

	// DiscountExpiresAt When the current discount expires (null if no active discount)
	DiscountExpiresAt *string `json:"discount_expires_at,omitempty"`

	// FreePagesRemaining Free pages remaining (lifetime credit)
	FreePagesRemaining int64 `json:"free_pages_remaining"`

	// FreePagesTotal Total free pages originally granted
	FreePagesTotal int64 `json:"free_pages_total"`

	// HasPaymentMethod Whether a Stripe payment method is on file
	HasPaymentMethod bool `json:"has_payment_method"`

	// PriceTier Current price tier (STANDARD or DISCOUNTED)
	PriceTier string `json:"price_tier"`

	// SubscriptionStatus Stripe subscription status ("active", "past_due", "canceled", etc.).
	// Null when no subscription exists on the billing account.
	SubscriptionStatus *string `json:"subscription_status,omitempty"`
}

// BillingResponse Billing and quota response for a project
type BillingResponse struct {
	BillingAccount *BillingAccountInfo `json:"billing_account,omitempty"`

	// PeriodEnd End of the current billing period (ISO 8601 date)
	PeriodEnd string `json:"period_end"`

	// PeriodStart Start of the current billing period (ISO 8601 date)
	PeriodStart string `json:"period_start"`

	// Plan Plan limits
	Plan PlanInfo `json:"plan"`

	// ProjectId The project identifier
	ProjectId string `json:"project_id"`

	// Usage Current usage within the billing period
	Usage UsageInfo `json:"usage"`
}

// CheckoutResponse Response body for a Stripe Checkout Session
type CheckoutResponse struct {
	// Url Stripe Checkout Session URL to redirect the user to
	Url string `json:"url"`
}

// CreateInvitationRequest Request to create a project invitation.
type CreateInvitationRequest struct {
	// Email Email address to invite.
	Email string `json:"email"`

	// Role Role to assign: `"OWNER"` or `"MEMBER"`.
	Role string `json:"role"`
}

// CreateInvitationResponse Response returned when creating an invitation. Includes the plaintext
// token (for email delivery by the caller) and omits `status`/`created_at`,
// which are implicit (`PENDING`, "now") at creation time.
type CreateInvitationResponse struct {
	// Email Invited email address.
	Email string `json:"email"`

	// ExpiresAt ISO 8601 expiration timestamp.
	ExpiresAt string `json:"expires_at"`

	// Id Unique invitation identifier.
	Id string `json:"id"`

	// Role Assigned role.
	Role string `json:"role"`

	// Token Invitation token to include in the invitation email link. Only
	// returned once, at creation time.
	Token string `json:"token"`
}

// CreateWebhookRequest Request to create a new webhook.
type CreateWebhookRequest struct {
	// Events Event types to subscribe to.
	Events []string `json:"events"`

	// Name Webhook display name.
	Name string `json:"name"`

	// Secret Optional HMAC secret. Generated server-side when not provided.
	Secret *string `json:"secret,omitempty"`

	// Url Webhook delivery URL (must use HTTPS).
	Url string `json:"url"`
}

// DailyAnalyticsEntry Daily analytics record
type DailyAnalyticsEntry struct {
	// Date Date (ISO 8601 format)
	Date string `json:"date"`

	// FileTypes File type breakdown (MIME type → count)
	FileTypes interface{} `json:"file_types"`

	// JobsCancelled Cancelled jobs
	JobsCancelled int32 `json:"jobs_cancelled"`

	// JobsCompleted Successfully completed jobs
	JobsCompleted int32 `json:"jobs_completed"`

	// JobsFailed Failed jobs
	JobsFailed int32 `json:"jobs_failed"`

	// JobsTotal Total jobs submitted
	JobsTotal       int32                 `json:"jobs_total"`
	ProcessingStats *ProcessingStatsEntry `json:"processing_stats,omitempty"`

	// TotalFileSizeBytes Total file size processed in bytes
	TotalFileSizeBytes int64 `json:"total_file_size_bytes"`

	// TotalImagesExtracted Total images extracted
	TotalImagesExtracted int32 `json:"total_images_extracted"`

	// TotalPagesExtracted Total pages extracted
	TotalPagesExtracted int32 `json:"total_pages_extracted"`

	// TotalProcessingTimeMs Total processing time across all jobs in milliseconds
	TotalProcessingTimeMs int64 `json:"total_processing_time_ms"`

	// TotalTablesExtracted Total tables extracted
	TotalTablesExtracted int32 `json:"total_tables_extracted"`
}

// ErrorDetail Error detail for failed requests
type ErrorDetail struct {
	// ErrorMessage Error message
	ErrorMessage *string `json:"error_message,omitempty"`

	// Method HTTP method
	Method string `json:"method"`

	// Path Request path
	Path string `json:"path"`

	// StatusCode HTTP status code
	StatusCode int32 `json:"status_code"`

	// Timestamp ISO 8601 timestamp of the error
	Timestamp string `json:"timestamp"`
}

// InvitationResponse Invitation details, as returned by list.
type InvitationResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt string `json:"created_at"`

	// Email Invited email address.
	Email string `json:"email"`

	// ExpiresAt ISO 8601 expiration timestamp.
	ExpiresAt string `json:"expires_at"`

	// Id Unique invitation identifier.
	Id string `json:"id"`

	// Role Assigned role.
	Role string `json:"role"`

	// Status Invitation status (e.g. `"PENDING"`, `"ACCEPTED"`, `"REVOKED"`).
	Status string `json:"status"`
}

// ListDocumentsQuery Query parameters for listing integration documents
type ListDocumentsQuery struct {
	// FolderId Source-specific folder ID to restrict results to (e.g., Google Drive folder ID).
	// If not provided, lists documents from the root/default location.
	FolderId *string `json:"folder_id,omitempty"`

	// MaxResults Maximum number of documents to return. Clamped to 1000 maximum.
	// If not provided, uses the connector's default.
	MaxResults *int `json:"max_results,omitempty"`

	// MimeTypes Comma-separated MIME types to filter by (e.g., "text/plain,application/pdf").
	// If not provided, all document types are returned.
	MimeTypes *string `json:"mime_types,omitempty"`
}

// ListInvitationsResponse Response for the paginated pending-invitation list endpoint.
type ListInvitationsResponse struct {
	// Invitations Pending invitations in the current page.
	Invitations []InvitationResponse `json:"invitations"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of pending invitations for the project.
	Total int64 `json:"total"`
}

// ListMembersResponse Response for the paginated project member list endpoint.
type ListMembersResponse struct {
	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Members Members in the current page.
	Members []MemberResponse `json:"members"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of members in the project.
	Total int64 `json:"total"`
}

// ListWebhookDeliveriesResponse Response for the paginated webhook delivery-history endpoint.
type ListWebhookDeliveriesResponse struct {
	// Deliveries Delivery attempts in the current page, newest first.
	Deliveries []WebhookDeliveryResponse `json:"deliveries"`

	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of delivery attempts recorded for the webhook.
	Total int64 `json:"total"`
}

// ListWebhooksResponse Response for the paginated webhook list endpoint.
type ListWebhooksResponse struct {
	// Limit Page size used.
	Limit int64 `json:"limit"`

	// Offset Offset used for pagination.
	Offset int64 `json:"offset"`

	// Total Total number of webhooks for the project.
	Total int64 `json:"total"`

	// Webhooks Webhooks in the current page.
	Webhooks []WebhookResponse `json:"webhooks"`
}

// MemberResponse Project member details.
type MemberResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt string `json:"created_at"`

	// DisplayName Member's display name, when known.
	DisplayName *string `json:"display_name,omitempty"`

	// Email Member's email address, when known.
	Email *string `json:"email,omitempty"`

	// Id Unique member identifier.
	Id string `json:"id"`

	// Role Member's role in the project (e.g. `"OWNER"`, `"MEMBER"`).
	Role string `json:"role"`

	// UserId User ID of the member.
	UserId string `json:"user_id"`
}

// MimeTypeUsage Per-MIME-type usage breakdown
type MimeTypeUsage struct {
	// Documents Number of documents processed
	Documents int32 `json:"documents"`

	// Failed Number of failed documents
	Failed int32 `json:"failed"`

	// Pages Total pages extracted
	Pages int64 `json:"pages"`
}

// PlanInfo Plan limits for the project
type PlanInfo struct {
	// MaxFileSizeMb Maximum file size in megabytes (null = unlimited)
	MaxFileSizeMb *int32 `json:"max_file_size_mb,omitempty"`

	// MaxMonthlyJobs Maximum jobs allowed per month (null = unlimited)
	MaxMonthlyJobs *int64 `json:"max_monthly_jobs,omitempty"`

	// MaxMonthlyPages Maximum pages allowed per month (null = unlimited)
	MaxMonthlyPages *int64 `json:"max_monthly_pages,omitempty"`
}

// PortalResponse Response body for a Stripe Customer Portal Session
type PortalResponse struct {
	// Url Stripe Customer Portal URL to redirect the user to
	Url string `json:"url"`
}

// ProcessingStatsEntry Processing time percentiles for a day
type ProcessingStatsEntry struct {
	// P50Ms Median processing time in milliseconds
	P50Ms *int64 `json:"p50_ms,omitempty"`

	// P95Ms 95th percentile processing time in milliseconds
	P95Ms *int64 `json:"p95_ms,omitempty"`

	// P99Ms 99th percentile processing time in milliseconds
	P99Ms *int64 `json:"p99_ms,omitempty"`

	// SampleCount Number of samples used for calculation
	SampleCount int32 `json:"sample_count"`
}

// PublicSandboxExtractForm Multipart form fields accepted by the public sandbox extract endpoint.
//
// Documented so the generated OpenAPI client is aware of every field; the
// handler parses the multipart body manually rather than deserializing this
// type. `file` is required for every mode except `web`, which reads `url`.
type PublicSandboxExtractForm struct {
	// File Document to extract (required for all modes except `web`). Max 1 MB.
	File openapi_types.File `json:"file"`

	// Mode Extraction mode: `extract` (default), `rag`, `idp`, `code`, `web`.
	Mode *string `json:"mode,omitempty"`

	// Preset Curated preset id — required for `idp` mode (validated against the embedded registry).
	Preset *string `json:"preset,omitempty"`

	// Url Seed URL to crawl — required for `web` mode.
	Url *string `json:"url,omitempty"`
}

// RetryWebhookDeliveryResponse A manual redelivery request has been queued. Delivery itself happens out
// of band (the same NATS-consumer delivery path automatic retries use), so
// this is an accepted-style response rather than a completed delivery
// record: the caller polls `GET .../deliveries` to observe the outcome.
type RetryWebhookDeliveryResponse struct {
	// DeliveryId Identifier of the new delivery attempt created for this retry.
	DeliveryId openapi_types.UUID `json:"delivery_id"`

	// QueuedAt ISO 8601 timestamp the retry was queued at.
	QueuedAt string `json:"queued_at"`

	// Status Always `"queued"` today; a stable string so future states
	// (`"delivered"`, `"failed"`) can be added without a breaking change.
	Status string `json:"status"`
}

// SandboxExtractResponse Sandbox extraction response — mirrors the real API `GET /v1/jobs/{id}` response
type SandboxExtractResponse struct {
	// CreatedAt Job creation timestamp (RFC3339)
	CreatedAt string `json:"created_at"`

	// Filename Original filename
	Filename string `json:"filename"`

	// Id Unique job identifier (UUID)
	Id string `json:"id"`

	// ProcessingTimeMs Processing time in milliseconds
	ProcessingTimeMs *int64             `json:"processing_time_ms,omitempty"`
	Result           *ExtractedDocument `json:"result,omitempty"`

	// Status Job status
	Status string `json:"status"`
}

// UpdateMemberRoleRequest Request to update a member's role within a project.
type UpdateMemberRoleRequest struct {
	// Role New role: `"OWNER"` or `"MEMBER"`.
	Role string `json:"role"`
}

// UpdateProjectRequest Request to update an existing project. Enterprise-only today (Pro has no
// project-update endpoint).
type UpdateProjectRequest struct {
	// Name Updated project name.
	Name *string `json:"name,omitempty"`
}

// UpdateWebhookRequest Request to update a webhook. All fields optional; at least one must be
// set for the update to be meaningful.
type UpdateWebhookRequest struct {
	// Events Updated event subscription list.
	Events *[]string `json:"events,omitempty"`

	// IsActive Updated active status.
	IsActive *bool `json:"is_active,omitempty"`

	// Name Updated webhook name.
	Name *string `json:"name,omitempty"`

	// Url Updated webhook URL.
	Url *string `json:"url,omitempty"`
}

// UsageInfo Current usage for the billing period
type UsageInfo struct {
	// ByMimeType Usage breakdown by MIME type
	ByMimeType map[string]MimeTypeUsage `json:"by_mime_type"`

	// PagesRemaining Pages remaining before hitting the limit (null = unlimited)
	PagesRemaining *int64 `json:"pages_remaining,omitempty"`

	// PagesUsed Total pages used in the current period
	PagesUsed int64 `json:"pages_used"`

	// TotalDocuments Total documents processed
	TotalDocuments int32 `json:"total_documents"`

	// TotalFailed Total failed documents
	TotalFailed int32 `json:"total_failed"`
}

// UsagePeriod Period details in usage response
type UsagePeriod struct {
	// EndDate End date (ISO 8601 format)
	EndDate string `json:"end_date"`

	// StartDate Start date (ISO 8601 format)
	StartDate string `json:"start_date"`
}

// UsageQuery Query parameters for usage statistics endpoint
type UsageQuery struct {
	// EndDate End date for the usage period (ISO 8601 format, e.g., "2025-01-31")
	EndDate string `json:"end_date"`

	// StartDate Start date for the usage period (ISO 8601 format, e.g., "2025-01-01")
	StartDate string `json:"start_date"`
}

// UsageSummary Summary statistics for a usage period
type UsageSummary struct {
	// AverageResponseTimeMs Average response time in milliseconds
	AverageResponseTimeMs int32 `json:"average_response_time_ms"`

	// FailedRequests Number of failed requests (status >= 400)
	FailedRequests int64 `json:"failed_requests"`

	// SuccessfulRequests Number of successful requests (status < 400)
	SuccessfulRequests int64 `json:"successful_requests"`

	// TotalRequestBytes Total request size in bytes
	TotalRequestBytes int64 `json:"total_request_bytes"`

	// TotalRequests Total number of requests
	TotalRequests int64 `json:"total_requests"`

	// TotalResponseBytes Total response size in bytes
	TotalResponseBytes int64 `json:"total_response_bytes"`
}

// WebhookDeliveryResponse One past delivery attempt for a webhook subscription.
//
// **Payload bodies are deliberately not included here.** A delivery's
// request and response bodies can carry document extraction content — the
// same `results` payload `WebhookEvent` embeds — which is exactly the class
// of data `WEBHOOK_RESULTS_MAX_BYTES` already treats as too sensitive/large
// to always inline. A list endpoint that paginates delivery *metadata*
// should not also be the place a caller incidentally pages through
// potentially large document content: that argues for a separate
// `GET .../deliveries/{delivery_id}` detail endpoint fetched on demand (not
// declared by this pass — only the list and retry operations are), the same
// "small by default, fetch the rest separately" shape the job-result and
// webhook-event payloads already use.
type WebhookDeliveryResponse struct {
	// AttemptNumber 1-based attempt number within the redelivery sequence for this event
	// (bounded by `WEBHOOK_MAX_ATTEMPTS` in `common::webhook`).
	AttemptNumber int32 `json:"attempt_number"`

	// DurationMs How long the delivery attempt took, in milliseconds.
	DurationMs int64 `json:"duration_ms"`

	// Error Error message, present when the attempt did not succeed.
	Error *string `json:"error,omitempty"`

	// EventType The event type delivered (e.g. `"job.completed"`, `"job.failed"`).
	EventType string `json:"event_type"`

	// Id Unique identifier of this delivery attempt.
	Id openapi_types.UUID `json:"id"`

	// JobId The job this delivery attempt carries the event for.
	JobId string `json:"job_id"`

	// OccurredAt ISO 8601 timestamp the attempt occurred at.
	OccurredAt string `json:"occurred_at"`

	// StatusCode HTTP status code returned by the endpoint, when a response was
	// received at all (absent on a connection/timeout failure).
	StatusCode *int32 `json:"status_code,omitempty"`

	// Success Whether the endpoint accepted the delivery.
	Success bool `json:"success"`
}

// WebhookResponse Webhook resource details.
type WebhookResponse struct {
	// CreatedAt ISO 8601 creation timestamp.
	CreatedAt string `json:"created_at"`

	// Events Subscribed event types (e.g. `"job.completed"`, `"job.failed"`).
	Events []string `json:"events"`

	// FailedDeliveries Number of failed delivery attempts.
	FailedDeliveries int32 `json:"failed_deliveries"`

	// Id Unique webhook identifier.
	Id openapi_types.UUID `json:"id"`

	// IsActive Whether the webhook is currently active.
	IsActive bool `json:"is_active"`

	// LastDeliveryAt ISO 8601 timestamp of the last delivery attempt.
	LastDeliveryAt *string `json:"last_delivery_at,omitempty"`

	// LastDeliveryStatus Status of the last delivery attempt (e.g. `"success"`, `"failed"`).
	LastDeliveryStatus *string `json:"last_delivery_status,omitempty"`

	// Name Webhook display name.
	Name string `json:"name"`

	// TotalDeliveries Total number of delivery attempts.
	TotalDeliveries int32 `json:"total_deliveries"`

	// UpdatedAt ISO 8601 last update timestamp.
	UpdatedAt string `json:"updated_at"`

	// Url Webhook delivery URL.
	Url string `json:"url"`
}

// WebhookTestResponse Result of a manual test delivery to a webhook endpoint.
type WebhookTestResponse struct {
	// Error Error message, when the delivery failed.
	Error *string `json:"error,omitempty"`

	// StatusCode HTTP status code returned by the webhook endpoint, when reached.
	StatusCode *int32 `json:"status_code,omitempty"`

	// Success Whether the test delivery was successful.
	Success bool `json:"success"`
}

// DeleteProjectParams defines parameters for DeleteProject.
type DeleteProjectParams struct {
	// Erase Erase the project's content, not only its rows.
	//
	// Without it the delete is what this route has always done: the rows are
	// tombstoned and the caches are purged. With `erase=true` the stored
	// documents, the cached results, the vector chunks and the retrieval
	// audit rows go as well, and none of it comes back.
	Erase *bool `form:"erase,omitempty" json:"erase,omitempty"`
}

// GetAnalyticsParams defines parameters for GetAnalytics.
type GetAnalyticsParams struct {
	// StartDate Start date (ISO 8601 format, e.g., "2025-01-01")
	StartDate string `form:"start_date" json:"start_date"`

	// EndDate End date (ISO 8601 format, e.g., "2025-01-31")
	EndDate string `form:"end_date" json:"end_date"`
}

// ListProjectAuditParams defines parameters for ListProjectAudit.
type ListProjectAuditParams struct {
	// Action Optional action filter, e.g. api_key.create
	Action *string `form:"action,omitempty" json:"action,omitempty"`

	// Limit Page size (default 50, max 100)
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset (default 0)
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListInvitationsParams defines parameters for ListInvitations.
type ListInvitationsParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// SandboxExtractMultipartBody defines parameters for SandboxExtract.
type SandboxExtractMultipartBody interface{}

// ListWebhooksParams defines parameters for ListWebhooks.
type ListWebhooksParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListWebhookDeliveriesParams defines parameters for ListWebhookDeliveries.
type ListWebhookDeliveriesParams struct {
	// Limit Page size. A value outside 1..=1000 is rejected with a 400, on both
	// tiers.
	Limit *int64 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip. A negative value is rejected with a 400; a
	// value above 1,000,000 is accepted but clamped to 1,000,000, which
	// selects an empty page rather than erroring.
	Offset *int64 `form:"offset,omitempty" json:"offset,omitempty"`
}

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = AcceptInvitationRequest

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = UpdateProjectRequest

// InviteUserJSONRequestBody defines body for InviteUser for application/json ContentType.
type InviteUserJSONRequestBody = CreateInvitationRequest

// UpdateMemberRoleJSONRequestBody defines body for UpdateMemberRole for application/json ContentType.
type UpdateMemberRoleJSONRequestBody = UpdateMemberRoleRequest

// SandboxExtractMultipartRequestBody defines body for SandboxExtract for multipart/form-data ContentType.
type SandboxExtractMultipartRequestBody SandboxExtractMultipartBody

// CreateWebhookJSONRequestBody defines body for CreateWebhook for application/json ContentType.
type CreateWebhookJSONRequestBody = CreateWebhookRequest

// UpdateWebhookJSONRequestBody defines body for UpdateWebhook for application/json ContentType.
type UpdateWebhookJSONRequestBody = UpdateWebhookRequest

// PublicSandboxExtractMultipartRequestBody defines body for PublicSandboxExtract for multipart/form-data ContentType.
type PublicSandboxExtractMultipartRequestBody = PublicSandboxExtractForm
