import { describe, expect, it } from "vitest";
import {
  AuthError,
  NotFoundError,
  RateLimitError,
  ServerError,
  SUCCESS_JOB_STATUSES,
  TERMINAL_JOB_STATUSES,
  TimeoutError,
  ValidationError,
  XbergClient,
  XbergError,
  createClient,
} from "../src/index.js";
import type {
  ApiKeyResponse,
  ApiKeyScope,
  AuditParams,
  AuthConfigResponse,
  AutoTuneCapabilitiesResponse,
  AutoTuneJobStatus,
  AutoTuneJobSummary,
  AutoTuneResult,
  BackoffStrategy,
  BeginOAuthResponse,
  ConfirmUploadRequest,
  ConfirmUploadResponse,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  CreateAutoTuneJobRequest,
  CreateAutoTuneJobResponse,
  CreateClientOptions,
  CreateIntegrationRequest,
  CreateProjectRequest,
  CreateSavedPresetRequest,
  CreateSavedPresetResponse,
  DiffResponse,
  DocumentInput,
  DocumentResponse,
  DocumentVersionEntry,
  EnrichJobStatus,
  EnrichJobSubmitted,
  EnrichRequestOptions,
  EnrichTextRequest,
  ExtractAndWaitParams,
  ExtractBatchParams,
  ExtractedDocument,
  ExtractionConfig,
  ExtractionEventSummary,
  ExtractionOptions,
  ExtractionResult,
  ExtractParams,
  ExtractResponse,
  FileLike,
  GetJobResponse,
  IntegrationResponse,
  Job,
  JobResult,
  JobResultError,
  JobStatus,
  LicenseInfoResponse,
  ListApiKeysResponse,
  ListAuditEntriesResponse,
  ListAutoTuneJobsResponse,
  ListDocumentsResponse,
  ListExtractionEventsParams,
  ListExtractionEventsResponse,
  ListIntegrationDocumentsParams,
  ListIntegrationsResponse,
  ListJobsParams,
  ListJobsResponse,
  ListManagedEmbeddingPresetsResponse,
  ListProjectsResponse,
  ListSavedPresetsResponse,
  ListTuningProfilesResponse,
  ListWebhookDeliveriesResponse,
  LoginRequest,
  LoginResponse,
  ManagedEmbeddingPreset,
  PaginationParams,
  PresetDetail,
  PresetSummary,
  PresignUploadRequest,
  PresignUploadResponse,
  ProjectResponse,
  PromoteProfileRequest,
  RagConfigResponse,
  RateLimitErrorOptions,
  SavedPresetDetail,
  SavedPresetSummary,
  SetRagConfigRequest,
  SubmitAutoTuneParams,
  Target,
  TuningProfileDetail,
  TuningProfileSummary,
  UpdateSavedPresetRequest,
  UpdateSavedPresetResponse,
  UsageResponse,
  WaitOptions,
  WebhookConfig,
  WebhookDeliveryDetailResponse,
  XbergClientOptions,
  XbergErrorOptions,
  XbergRawClient,
  components,
  paths,
  proComponents,
  proPaths,
} from "../src/index.js";

describe("index re-exports", () => {
  it("re-exports the client value exports with the correct runtime type", () => {
    expect(typeof XbergClient).toBe("function");
    expect(typeof createClient).toBe("function");
  });

  it("re-exports the error class hierarchy with the correct runtime type", () => {
    expect(typeof XbergError).toBe("function");
    expect(typeof AuthError).toBe("function");
    expect(typeof NotFoundError).toBe("function");
    expect(typeof RateLimitError).toBe("function");
    expect(typeof ServerError).toBe("function");
    expect(typeof TimeoutError).toBe("function");
    expect(typeof ValidationError).toBe("function");
  });

  it("re-exports the exact SUCCESS_JOB_STATUSES value from types.ts", () => {
    expect(SUCCESS_JOB_STATUSES).toEqual(["completed", "partial_success"]);
  });

  it("re-exports the exact TERMINAL_JOB_STATUSES value from types.ts", () => {
    expect(TERMINAL_JOB_STATUSES).toEqual(["completed", "partial_success", "failed", "cancelled"]);
  });

  it("re-exported error classes form the expected instanceof chain", () => {
    const authError = new AuthError("nope", { status: 401, body: null });
    expect(authError).toBeInstanceOf(XbergError);
    expect(authError).toBeInstanceOf(Error);
  });
});

// Type-only exports vanish at compile time; importing them here proves the
// export exists and compiles without needing a runtime assertion.
type _TypeOnlyExportsCompile = [
  ApiKeyResponse,
  ApiKeyScope,
  AuditParams,
  AuthConfigResponse,
  AutoTuneCapabilitiesResponse,
  AutoTuneJobStatus,
  AutoTuneJobSummary,
  AutoTuneResult,
  BackoffStrategy,
  BeginOAuthResponse,
  ConfirmUploadRequest,
  ConfirmUploadResponse,
  CreateApiKeyRequest,
  CreateApiKeyResponse,
  CreateAutoTuneJobRequest,
  CreateAutoTuneJobResponse,
  CreateClientOptions,
  CreateIntegrationRequest,
  CreateProjectRequest,
  CreateSavedPresetRequest,
  CreateSavedPresetResponse,
  DiffResponse,
  DocumentInput,
  DocumentResponse,
  DocumentVersionEntry,
  EnrichJobStatus,
  EnrichJobSubmitted,
  EnrichRequestOptions,
  EnrichTextRequest,
  ExtractAndWaitParams,
  ExtractBatchParams,
  ExtractedDocument,
  ExtractionConfig,
  ExtractionEventSummary,
  ExtractionOptions,
  ExtractionResult,
  ExtractParams,
  ExtractResponse,
  FileLike,
  GetJobResponse,
  IntegrationResponse,
  Job,
  JobResult,
  JobResultError,
  JobStatus,
  LicenseInfoResponse,
  ListApiKeysResponse,
  ListAuditEntriesResponse,
  ListAutoTuneJobsResponse,
  ListDocumentsResponse,
  ListExtractionEventsParams,
  ListExtractionEventsResponse,
  ListIntegrationDocumentsParams,
  ListIntegrationsResponse,
  ListJobsParams,
  ListJobsResponse,
  ListManagedEmbeddingPresetsResponse,
  ListProjectsResponse,
  ListSavedPresetsResponse,
  ListTuningProfilesResponse,
  ListWebhookDeliveriesResponse,
  LoginRequest,
  LoginResponse,
  ManagedEmbeddingPreset,
  PaginationParams,
  PresetDetail,
  PresetSummary,
  PresignUploadRequest,
  PresignUploadResponse,
  ProjectResponse,
  PromoteProfileRequest,
  RagConfigResponse,
  RateLimitErrorOptions,
  SavedPresetDetail,
  SavedPresetSummary,
  SetRagConfigRequest,
  SubmitAutoTuneParams,
  Target,
  TuningProfileDetail,
  TuningProfileSummary,
  UpdateSavedPresetRequest,
  UpdateSavedPresetResponse,
  UsageResponse,
  WaitOptions,
  WebhookConfig,
  WebhookDeliveryDetailResponse,
  XbergClientOptions,
  XbergErrorOptions,
  XbergRawClient,
  components,
  paths,
  proComponents,
  proPaths,
];
