"""High-level wrappers around the kreuzberg-cloud HTTP API.

The classes in this module wrap the underlying transport in an idiomatic,
ergonomic shape — handling authentication, base URL configuration, resource
lifecycle, multipart upload encoding, and job polling — without hiding the
typed models generated by ``openapi-python-client`` (re-exported from the
package root).
"""

from __future__ import annotations

import asyncio
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any, BinaryIO, Literal

import httpx

from kreuzberg_cloud._generated.models.extraction_options import ExtractionOptions
from kreuzberg_cloud._generated.models.job_response import JobResponse
from kreuzberg_cloud.errors import TimeoutError as ClientTimeoutError
from kreuzberg_cloud.errors import raise_for_status
from kreuzberg_cloud.models import SandboxKey

if sys.version_info >= (3, 11):
    from typing import Self
else:
    from typing_extensions import Self

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping
    from types import TracebackType

DEFAULT_BASE_URL = "https://api.kreuzberg.cloud"
DEFAULT_TIMEOUT_SECONDS = 30.0
_USER_AGENT = "kreuzberg-cloud-python/0.0.1"

_TERMINAL_STATUSES: frozenset[str] = frozenset({"completed", "failed", "cancelled", "partial_success"})
_FAILED_STATUSES: frozenset[str] = frozenset({"failed", "cancelled"})

_DEFAULT_POLL_INTERVAL = 1.0
_DEFAULT_WAIT_TIMEOUT = 300.0
_MAX_BACKOFF_INTERVAL = 30.0
_BACKOFF_FACTOR = 2.0

FileInput = Path | bytes | BinaryIO
"""Accepted shapes for a single file argument: filesystem path, raw bytes, or an open binary stream."""

OptionsInput = ExtractionOptions | dict[str, Any] | None
"""Accepted shapes for the ``options`` argument: typed model, plain dict, or ``None``."""

BackoffStrategy = Literal["constant", "exponential"]


def _coerce_options(options: OptionsInput) -> dict[str, Any] | None:
    """Normalize an :class:`ExtractionOptions`/dict/``None`` into a plain dict (or ``None``)."""
    if options is None:
        return None
    if isinstance(options, ExtractionOptions):
        return options.to_dict()
    return dict(options)


def _prepare_file_part(file: FileInput) -> tuple[str, bytes | BinaryIO, str]:
    """Convert a ``FileInput`` into the ``(filename, payload, content-type)`` tuple httpx wants.

    - :class:`Path`: read bytes, infer filename from path, fall back to octet-stream MIME.
    - :class:`bytes`: synthetic ``upload.bin`` filename.
    - File-like: probe ``.name`` for a filename, fall back to ``upload.bin``.
    """
    if isinstance(file, Path):
        return (file.name, file.read_bytes(), "application/octet-stream")
    if isinstance(file, (bytes, bytearray)):
        return ("upload.bin", bytes(file), "application/octet-stream")
    name = getattr(file, "name", None)
    filename = Path(str(name)).name if isinstance(name, str) and name else "upload.bin"
    return (filename, file, "application/octet-stream")


def _multipart_files(file: FileInput) -> list[tuple[str, tuple[str, bytes | BinaryIO, str]]]:
    """Build the ``files=`` argument for ``httpx`` multipart upload of a single document."""
    return [("files", _prepare_file_part(file))]


def _multipart_data(options: OptionsInput) -> dict[str, str] | None:
    """Build the ``data=`` argument carrying serialized options as a JSON-encoded multipart part."""
    coerced = _coerce_options(options)
    if coerced is None:
        return None
    import json  # local import — keeps stdlib import out of hot path  # noqa: PLC0415

    return {"options": json.dumps(coerced)}


def _job_id_from_extract_response(payload: Any) -> str:
    """Pluck the first job id out of a ``POST /v1/extract`` response body."""
    if not isinstance(payload, dict):
        raise ValueError(f"unexpected extract response shape: {payload!r}")
    job_ids = payload.get("job_ids")
    if not isinstance(job_ids, list) or not job_ids:
        raise ValueError(f"extract response missing job_ids: {payload!r}")
    return str(job_ids[0])


def _parse_job(payload: Any) -> JobResponse:
    """Parse a ``GET /v1/jobs/{id}`` response body into a typed :class:`JobResponse`."""
    if not isinstance(payload, dict):
        raise ValueError(f"unexpected job response shape: {payload!r}")
    return JobResponse.from_dict(payload)


def _next_interval(current: float, backoff: BackoffStrategy) -> float:
    """Advance the polling interval according to the configured backoff strategy."""
    if backoff == "constant":
        return current
    return min(current * _BACKOFF_FACTOR, _MAX_BACKOFF_INTERVAL)


class _BaseClient:
    """Shared configuration for the sync and async clients."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout
        self._headers: dict[str, str] = {"User-Agent": _USER_AGENT}
        if headers:
            self._headers.update(headers)
        if api_key is not None:
            self._headers["Authorization"] = f"Bearer {api_key}"


class KreuzbergCloud(_BaseClient):
    """Synchronous client for the Kreuzberg Cloud API.

    Use as a context manager to ensure the underlying HTTP connection pool is
    closed:

    >>> with KreuzbergCloud(api_key="...") as client:  # doctest: +SKIP
    ...     job = client.extract(file=Path("invoice.pdf"))
    ...     result = client.wait_for_job(job.id)
    """

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        super().__init__(api_key=api_key, base_url=base_url, timeout=timeout, headers=headers)
        self._http = httpx.Client(base_url=self._base_url, timeout=self._timeout, headers=self._headers)

    def __enter__(self) -> Self:
        """Enter the context manager."""
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        """Exit the context manager and close the underlying HTTP transport."""
        self.close()

    def close(self) -> None:
        """Close the underlying HTTP transport, releasing connections."""
        self._http.close()

    def extract(self, *, file: FileInput, options: OptionsInput = None) -> JobResponse:
        """Submit a single document for extraction via ``POST /v1/extract`` (multipart).

        Returns a :class:`JobResponse` with ``status='pending'`` — call
        :meth:`wait_for_job` (or use :meth:`extract_and_wait`) to obtain the
        finished extraction result.
        """
        response = self._http.post(
            "/v1/extract",
            files=_multipart_files(file),
            data=_multipart_data(options),
        )
        raise_for_status(response)
        job_id = _job_id_from_extract_response(response.json())
        return self.get_job(job_id)

    def extract_batch(
        self,
        files: Iterable[FileInput],
        options: OptionsInput = None,
    ) -> list[JobResponse]:
        """Submit multiple documents for extraction.

        Each file is sent as its own ``POST /v1/extract`` request — this keeps
        the per-job ``Job`` representation 1:1 with the request, simplifying
        downstream tracking. For the sync client the requests run sequentially.
        """
        return [self.extract(file=item, options=options) for item in files]

    def get_job(self, job_id: str) -> JobResponse:
        """Fetch a job's current status and (when terminal) its extraction result."""
        response = self._http.get(f"/v1/jobs/{job_id}")
        raise_for_status(response)
        return _parse_job(response.json())

    def wait_for_job(
        self,
        job_id: str,
        *,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> JobResponse:
        """Poll ``GET /v1/jobs/{id}`` until the job reaches a terminal status or ``timeout`` elapses.

        Raises :class:`kreuzberg_cloud.errors.TimeoutError` if the deadline is
        hit before the job reaches a terminal status. Failed/cancelled jobs are
        returned to the caller (not raised) — inspect ``job.status`` to branch.
        """
        deadline = time.monotonic() + timeout
        interval = poll_interval
        while True:
            job = self.get_job(job_id)
            if job.status in _TERMINAL_STATUSES:
                return job
            now = time.monotonic()
            if now >= deadline:
                raise ClientTimeoutError(
                    f"job {job_id} did not reach a terminal status within {timeout}s",
                    status_code=None,
                )
            sleep_for = min(interval, deadline - now)
            time.sleep(sleep_for)
            interval = _next_interval(interval, backoff)

    def wait_for_jobs(
        self,
        job_ids: Iterable[str],
        *,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> list[JobResponse]:
        """Wait for multiple jobs sequentially (sync); see :meth:`AsyncKreuzbergCloud.wait_for_jobs` for parallel."""
        return [
            self.wait_for_job(job_id, timeout=timeout, poll_interval=poll_interval, backoff=backoff)
            for job_id in job_ids
        ]

    def extract_and_wait(
        self,
        *,
        file: FileInput,
        options: OptionsInput = None,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> JobResponse:
        """Submit a document and block until extraction completes (or ``timeout`` is hit)."""
        job = self.extract(file=file, options=options)
        return self.wait_for_job(
            str(job.id),
            timeout=timeout,
            poll_interval=poll_interval,
            backoff=backoff,
        )

    def create_sandbox_key(self) -> SandboxKey:
        """Mint an ephemeral sandbox API key via ``POST /v1/sandbox/key`` (unauthenticated)."""
        response = self._http.post("/v1/sandbox/key")
        raise_for_status(response)
        return SandboxKey.from_dict(response.json())

    @classmethod
    def from_sandbox(
        cls,
        *,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
    ) -> Self:
        """Construct a client preconfigured with a fresh sandbox key.

        Convenience wrapper for the zero-friction onboarding path: spin up a
        bare client, mint a sandbox key, and return a new authenticated client.
        """
        bootstrap = cls(base_url=base_url, timeout=timeout)
        try:
            key = bootstrap.create_sandbox_key()
        finally:
            bootstrap.close()
        return cls(api_key=key.api_key, base_url=base_url, timeout=timeout)


class AsyncKreuzbergCloud(_BaseClient):
    """Asynchronous client for the Kreuzberg Cloud API.

    Mirrors :class:`KreuzbergCloud` method-for-method; everything is awaitable.

    >>> async with AsyncKreuzbergCloud(api_key="...") as client:  # doctest: +SKIP
    ...     result = await client.extract_and_wait(file=Path("invoice.pdf"))
    ...     print(result.result)
    """

    def __init__(
        self,
        *,
        api_key: str | None = None,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        super().__init__(api_key=api_key, base_url=base_url, timeout=timeout, headers=headers)
        self._http = httpx.AsyncClient(base_url=self._base_url, timeout=self._timeout, headers=self._headers)

    async def __aenter__(self) -> Self:
        """Enter the async context manager."""
        return self

    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc_val: BaseException | None,
        exc_tb: TracebackType | None,
    ) -> None:
        """Exit the async context manager and close the underlying HTTP transport."""
        await self.aclose()

    async def aclose(self) -> None:
        """Close the underlying async HTTP transport, releasing connections."""
        await self._http.aclose()

    async def extract(self, *, file: FileInput, options: OptionsInput = None) -> JobResponse:
        """Async equivalent of :meth:`KreuzbergCloud.extract`."""
        response = await self._http.post(
            "/v1/extract",
            files=_multipart_files(file),
            data=_multipart_data(options),
        )
        raise_for_status(response)
        job_id = _job_id_from_extract_response(response.json())
        return await self.get_job(job_id)

    async def extract_batch(
        self,
        files: Iterable[FileInput],
        options: OptionsInput = None,
    ) -> list[JobResponse]:
        """Submit multiple documents in parallel via ``asyncio.gather``."""
        materialized = list(files)
        coros = [self.extract(file=item, options=options) for item in materialized]
        return list(await asyncio.gather(*coros))

    async def get_job(self, job_id: str) -> JobResponse:
        """Async equivalent of :meth:`KreuzbergCloud.get_job`."""
        response = await self._http.get(f"/v1/jobs/{job_id}")
        raise_for_status(response)
        return _parse_job(response.json())

    async def wait_for_job(
        self,
        job_id: str,
        *,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> JobResponse:
        """Async equivalent of :meth:`KreuzbergCloud.wait_for_job`."""
        deadline = time.monotonic() + timeout
        interval = poll_interval
        while True:
            job = await self.get_job(job_id)
            if job.status in _TERMINAL_STATUSES:
                return job
            now = time.monotonic()
            if now >= deadline:
                raise ClientTimeoutError(
                    f"job {job_id} did not reach a terminal status within {timeout}s",
                    status_code=None,
                )
            sleep_for = min(interval, deadline - now)
            await asyncio.sleep(sleep_for)
            interval = _next_interval(interval, backoff)

    async def wait_for_jobs(
        self,
        job_ids: Iterable[str],
        *,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> list[JobResponse]:
        """Wait for multiple jobs concurrently."""
        coros = [
            self.wait_for_job(job_id, timeout=timeout, poll_interval=poll_interval, backoff=backoff)
            for job_id in job_ids
        ]
        return list(await asyncio.gather(*coros))

    async def extract_and_wait(
        self,
        *,
        file: FileInput,
        options: OptionsInput = None,
        timeout: float = _DEFAULT_WAIT_TIMEOUT,
        poll_interval: float = _DEFAULT_POLL_INTERVAL,
        backoff: BackoffStrategy = "exponential",
    ) -> JobResponse:
        """Submit a document and await extraction in a single call."""
        job = await self.extract(file=file, options=options)
        return await self.wait_for_job(
            str(job.id),
            timeout=timeout,
            poll_interval=poll_interval,
            backoff=backoff,
        )

    async def create_sandbox_key(self) -> SandboxKey:
        """Async equivalent of :meth:`KreuzbergCloud.create_sandbox_key`."""
        response = await self._http.post("/v1/sandbox/key")
        raise_for_status(response)
        return SandboxKey.from_dict(response.json())

    @classmethod
    async def from_sandbox(
        cls,
        *,
        base_url: str = DEFAULT_BASE_URL,
        timeout: float = DEFAULT_TIMEOUT_SECONDS,
    ) -> Self:
        """Async equivalent of :meth:`KreuzbergCloud.from_sandbox`."""
        bootstrap = cls(base_url=base_url, timeout=timeout)
        try:
            key = await bootstrap.create_sandbox_key()
        finally:
            await bootstrap.aclose()
        return cls(api_key=key.api_key, base_url=base_url, timeout=timeout)


# Re-export friendly aliases. The OpenAPI-generated symbols are kept available
# for power users who want the underlying types.
__all__ = [
    "AsyncKreuzbergCloud",
    "BackoffStrategy",
    "FileInput",
    "KreuzbergCloud",
    "OptionsInput",
]
